"""migration 3

Revision ID: 4a22caa281c3
Revises: 697f7dee46ee
Create Date: 2018-01-05 14:18:48.661122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a22caa281c3'
down_revision = '697f7dee46ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FeedEntryTest_TestEntryTitle_key', 'FeedEntryTest', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('FeedEntryTest_TestEntryTitle_key', 'FeedEntryTest', ['TestEntryTitle'])
    # ### end Alembic commands ###
