"""migration 2

Revision ID: 697f7dee46ee
Revises: b05347edaa5b
Create Date: 2018-01-05 14:11:40.323968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697f7dee46ee'
down_revision = 'b05347edaa5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FeedEntryTest', sa.Column('TestEntryTitle', sa.String(length=80), nullable=True))
    op.drop_constraint('FeedEntryTest_EntryTitle_key', 'FeedEntryTest', type_='unique')
    op.create_unique_constraint(None, 'FeedEntryTest', ['TestEntryTitle'])
    op.drop_column('FeedEntryTest', 'EntryTitle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FeedEntryTest', sa.Column('EntryTitle', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'FeedEntryTest', type_='unique')
    op.create_unique_constraint('FeedEntryTest_EntryTitle_key', 'FeedEntryTest', ['EntryTitle'])
    op.drop_column('FeedEntryTest', 'TestEntryTitle')
    # ### end Alembic commands ###
