"""initial migration

Revision ID: b05347edaa5b
Revises: 
Create Date: 2018-01-05 14:06:47.639348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05347edaa5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FeedEntryTest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('EntryTitle', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('EntryTitle')
    )
    op.add_column('FeedEntry', sa.Column('EntryDate', sa.DateTime(timezone=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FeedEntry', 'EntryDate')
    op.drop_table('FeedEntryTest')
    # ### end Alembic commands ###
