"""added vote and saves relationships

Revision ID: b38eb0c061ad
Revises: 
Create Date: 2018-08-05 15:03:37.760508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b38eb0c061ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saves',
    sa.Column('saver_id', sa.Integer(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['FeedEntry.id'], ),
    sa.ForeignKeyConstraint(['saver_id'], ['User.id'], )
    )
    op.create_table('votes',
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['FeedEntry.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['User.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('saves')
    # ### end Alembic commands ###
