"""empty message

Revision ID: c27a55cf18e1
Revises: 4a22caa281c3
Create Date: 2018-03-13 09:44:45.159389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c27a55cf18e1'
down_revision = '4a22caa281c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Feed_feedTitle_key', 'Feed', type_='unique')
    op.create_unique_constraint(None, 'Feed', ['feedURL'])
    op.drop_column('Feed', 'id')
    op.add_column('FeedEntry', sa.Column('feed_url', sa.String(), nullable=True))
    op.drop_constraint('FeedEntry_EntryTitle_key', 'FeedEntry', type_='unique')
    op.drop_constraint('FeedEntry_feed_id_fkey', 'FeedEntry', type_='foreignkey')
    op.create_foreign_key(None, 'FeedEntry', 'Feed', ['feed_url'], ['feedURL'])
    op.drop_column('FeedEntry', 'feed_id')
    op.drop_column('FeedEntry', 'FeedEntryVotes')
    op.add_column('FeedEntryTest', sa.Column('feed_url', sa.String(), nullable=True))
    op.create_foreign_key(None, 'FeedEntryTest', 'Feed', ['feed_url'], ['feedURL'])
    op.drop_constraint('NewFeed_feedTitle_key', 'NewFeed', type_='unique')
    op.create_unique_constraint(None, 'NewFeed', ['feedURL'])
    op.drop_column('NewFeed', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NewFeed', sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"NewFeed_id_seq"\'::regclass)'), nullable=False))
    op.drop_constraint(None, 'NewFeed', type_='unique')
    op.create_unique_constraint('NewFeed_feedTitle_key', 'NewFeed', ['feedTitle'])
    op.drop_constraint(None, 'FeedEntryTest', type_='foreignkey')
    op.drop_column('FeedEntryTest', 'feed_url')
    op.add_column('FeedEntry', sa.Column('FeedEntryVotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('FeedEntry', sa.Column('feed_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'FeedEntry', type_='foreignkey')
    op.create_foreign_key('FeedEntry_feed_id_fkey', 'FeedEntry', 'Feed', ['feed_id'], ['id'])
    op.create_unique_constraint('FeedEntry_EntryTitle_key', 'FeedEntry', ['EntryTitle'])
    op.drop_column('FeedEntry', 'feed_url')
    op.add_column('Feed', sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Feed_id_seq"\'::regclass)'), nullable=False))
    op.drop_constraint(None, 'Feed', type_='unique')
    op.create_unique_constraint('Feed_feedTitle_key', 'Feed', ['feedTitle'])
    # ### end Alembic commands ###
